# ibm-mq-operator-subscription.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-mq
  namespace: {{ .Values.operatornamespace }}
spec:
  channel: {{ .Values.channelversion }}
  installPlanApproval: Manual
  name: ibm-mq
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
